- Makefile
Add cross-platform support for macos in Makefile.
> Add cross-platform support for macos

- README.md
- client.go
- path.go
See #79
Implement all external commands for Windows
> Implement all external commands for Windows

- internal/hlsserver/server.go
Solves https://github.com/aler9/rtsp-simple-server/issues/415
> Fix CORS issues with HLS player using authorization

- internal/conf/path.go
Issue #470
Allow dot and tilde as part of the RTSP URL
Update error message
> Allow dot and tilde as part of the RTSP URL

- internal/conf/path.go
> Minor spelling fix

- README.md
> #514 - Update README.md - minor typo

- internal/core/externalauth.go
- internal/core/hls_muxer.go
- internal/core/hls_server_test.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_server_test.go
- internal/core/rtsp_conn.go
- internal/core/rtsp_server_test.go
- internal/core/rtsp_session.go
- rtsp-simple-server.yml
Do some dynamic authentication, such as token
> External authentication support send url raw query

- internal/hls/client.go
- internal/hls/client_test.go
- internal/hls/client_video_processor.go
Urls starting with // and urls with query string parsed improperly, this pull request fixes this.
> m3u8 relative url fixed (starting with // and with query string)

- go.mod
- go.sum
- internal/core/data.go
- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/hls_source_test.go
- internal/core/reader.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_source.go
- internal/core/rtsp_server_test.go
- internal/core/rtsp_session.go
- internal/core/rtsp_source.go
- internal/core/rtsp_source_test.go
- internal/core/stream.go
- internal/hls/client_test.go
- internal/hls/client_video_processor.go
- internal/hls/muxer.go
- internal/hls/muxer_test.go
- internal/hls/muxer_ts_generator.go
- internal/rtmp/conn.go
> Support dynamic H264 SPS/PPS

- .dockerignore
- .github/workflows/release.yml
- README.md
- scripts/dockerhub.mk
> Allow to use the Raspberry Pi Camera with Docker

- README.md
- internal/core/rtmp_conn.go
- internal/core/rtmp_source.go
- internal/rtmp/conn.go
- internal/rtmp/conn_test.go
> Support publishing with RTMP and H265 (for OBS Studio)

- internal/rtmp/rawmessage/reader.go
- internal/rtmp/rawmessage/writer.go
group together messages by using a buffered writer between the network connection and the WriteMessage() function
> rtmp server: improve efficiency of outgoing packets

- README.md
- internal/core/externalauth.go
- internal/core/hls_muxer.go
- internal/core/hls_server_test.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_server_test.go
- internal/core/rtsp_conn.go
- internal/core/rtsp_server_test.go
- internal/core/webrtc_server.go
- internal/highleveltests/hls_server_test.go
- rtsp-simple-server.yml
> Send additional fields to external authentication URL 

- README.md
- openwrt.mk
- openwrt/Makefile
- Tested on MIPS (Gl.Inet Mudi E750) with rtsp
> Add OpenWRT Makefile

- internal/rpicamera/exe/Makefile
- internal/rpicamera/rpicamera.go
> rpicamera: support libcamera 0.0.4

- Makefile
> rpicamera: fix segmentation fault with older Raspberry Pis and Docker

- apidocs/openapi.yaml
- internal/conf/conf.go
- internal/core/core.go
- internal/core/hls_muxer.go
- internal/core/hls_server.go
- rtsp-simple-server.yml
> hls muxer: add option to dump segments on disk (#1322)

- internal/conf/authmethod.go
- internal/conf/conf.go
- internal/conf/encryption.go
- internal/conf/hlsvariant.go
- internal/conf/logdestination.go
- internal/conf/loglevel.go
- internal/conf/path.go
- internal/conf/protocol.go
- internal/conf/sourceprotocol.go
- internal/core/api.go
- internal/core/path_manager.go
this allows to detect errors during cloning
> general: add Clone() method to Conf and PathConf

- internal/core/hls_index.html
- internal/core/webrtc_index.html
to improve the experience on mobile devices
> add viewport meta to hls and webrtc page

- README.md
- go.mod
- go.sum
- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/hls_source_test.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_source.go
- internal/core/rtsp_session.go
- internal/core/rtsp_source.go
- internal/core/stream.go
- internal/core/stream_format.go
- internal/core/udp_source.go
- internal/formatprocessor/generic_test.go
- internal/formatprocessor/h264.go
- internal/formatprocessor/h265.go
- internal/formatprocessor/mpeg2audio.go
- internal/formatprocessor/mpeg4audio.go
- internal/formatprocessor/opus.go
- internal/formatprocessor/processor.go
- internal/formatprocessor/vp9.go
- internal/rtmp/conn.go
- internal/rtmp/conn_test.go
- internal/rtmp/message/msg_audio.go
- internal/rtmp/message/reader_test.go
> support publishing, reading and proxying MP3 tracks with RTMP (#1102)

- internal/core/rtmp_conn.go
- internal/core/rtsp_session.go
> api: fix type of RTMPS readers

- internal/core/api.go
- internal/core/api_defs.go
- internal/core/api_test.go
> api: add item count to /list endpoints (#1813)

- internal/core/hls_manager.go
- internal/core/hls_muxer.go
> hls: fix 404 error when hlsAlwaysRemux and sourceOnDemand are both true (#1818)

- internal/core/authentication.go
- internal/core/hls_manager_test.go
- internal/core/rtmp_server_test.go
- internal/core/rtsp_server_test.go
- internal/highleveltests/hls_server_test.go
this fixes a regression introduced in v0.23.0
> restore sending session ID to external authentication

- internal/rtmp/rawmessage/writer.go
this was causing moments of silence and timing errors when reading with RTMP a stream originally published with RTSP or HLS.
> rtmp: fix timestamp conversion from RTSP/HLS to RTMP

- README.md
> update webrtc changes in README.

- .dockerignore
- Makefile
- README.md
- scripts/binaries.mk
- scripts/dockerhub.mk
Fixes #1771
* add ffmpeg variant
* remove 'v' prefix from tags
> improve Docker images (#1771)

- internal/core/path.go
> fix 'runOnDemandRestart: yes'

- internal/core/webrtc_publish_index.html
- internal/core/webrtc_read_index.html
> webrtc: fix using inline credentials in URLs (#1919)

- README.md
- internal/core/webrtc_session.go
> webrtc: fix memory leak when publishing or reading (#1884)

- internal/core/webrtc_http_server.go
- internal/core/webrtc_manager.go
- internal/core/webrtc_pc.go
- internal/core/webrtc_publish_index.html
- internal/core/webrtc_session.go
> webrtc: use audio full band and allow setting audio bitrate (#1908)

- apidocs/openapi.yaml
- internal/core/api.go
- internal/core/api_test.go
- internal/core/hls_manager.go
- internal/core/path_manager.go
- internal/core/rtmp_server.go
- internal/core/rtsp_server.go
- internal/core/webrtc_manager.go
> api: return 404 in /get and /kick endpoints (#1994)

- README.md
- internal/core/hls_http_server.go
- internal/core/webrtc_http_server.go
> hls, webrtc: add Authorization to Access-Control-Allow-Headers (#2018)

- internal/core/webrtc_publish_index.html
> webrtc: display publish-related errors in web page (#1836)

- apidocs/openapi.yaml
- internal/core/api_defs.go
- internal/core/api_test.go
- internal/core/hls_manager.go
- internal/core/path.go
- internal/core/path_manager.go
> api: add 'readyTime' to paths (#2049)

- apidocs/openapi.yaml
- internal/conf/path.go
- internal/core/rpicamera_source.go
- internal/rpicamera/exe/camera.cpp
- internal/rpicamera/exe/parameters.c
- internal/rpicamera/exe/parameters.h
- internal/rpicamera/params.go
- internal/rpicamera/rpicamera.go
- mediamtx.yml
> rpi camera: add rpiCameraHDR parameter (#1876)

- internal/core/hls_http_server.go
- internal/core/hls_manager_test.go
- internal/core/path.go
- internal/core/webrtc_http_server.go
- internal/core/webrtc_manager.go
- internal/core/webrtc_session.go
> webrtc: send session ID to external auth server (#1981)

- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/path.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_conn.go
- internal/core/rtsp_conn.go
- internal/core/rtsp_session.go
- internal/core/rtsp_source.go
- internal/core/udp_source.go
- internal/core/webrtc_incoming_track.go
- internal/core/webrtc_outgoing_track.go
- internal/core/webrtc_session.go
- internal/stream/stream.go
- internal/stream/stream_format.go
- internal/stream/stream_media.go
> move stream in a dedicated package

- internal/core/hls_source.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_conn.go
- internal/core/udp_source.go
- internal/formatprocessor/av1.go
- internal/formatprocessor/av1_test.go
- internal/formatprocessor/generic.go
- internal/formatprocessor/generic_test.go
- internal/formatprocessor/h264.go
- internal/formatprocessor/h264_test.go
- internal/formatprocessor/h265.go
- internal/formatprocessor/h265_test.go
- internal/formatprocessor/mpeg2audio.go
- internal/formatprocessor/mpeg4audio_generic.go
- internal/formatprocessor/mpeg4audio_latm.go
- internal/formatprocessor/opus.go
- internal/formatprocessor/unit.go
- internal/formatprocessor/vp8.go
- internal/formatprocessor/vp9.go
> add base class to all data units

- internal/core/hls_manager.go
- internal/core/hls_muxer.go
- internal/core/path.go
- internal/core/path_manager.go
- internal/core/rtmp_conn.go
- internal/core/rtsp_session.go
- internal/core/webrtc_http_server.go
- internal/core/webrtc_incoming_track.go
- internal/core/webrtc_manager.go
- internal/core/webrtc_session.go
> normalize channels and methods

- internal/rtmp/message/audio.go
- internal/rtmp/message/extended_coded_frames.go
- internal/rtmp/message/extended_frames_x.go
- internal/rtmp/message/extended_metadata.go
- internal/rtmp/message/extended_mpeg2ts_sequence_start.go
- internal/rtmp/message/extended_sequence_end.go
- internal/rtmp/message/extended_sequence_start.go
- internal/rtmp/message/message.go
- internal/rtmp/message/reader.go
- internal/rtmp/message/reader_test.go
- internal/rtmp/message/video.go
- internal/rtmp/reader.go
- internal/rtmp/reader_test.go
- mediamtx.yml
> support publishing AV1/H265 with OBS 30 (#2217)

- internal/core/webrtc_outgoing_track.go
- internal/stream/stream_format.go
> fix bug that prevented multiple readers from accessing the same stream (#2281)

- go.mod
- go.sum
- internal/core/udp_source.go
> udp: fix reading two streams with same port and different multicast IP (#2133)

- apidocs/openapi.yaml
> apidocs: mark discrete parameters as integers (#2331)

- internal/conf/conf.go
- internal/conf/conf_test.go
- internal/core/core.go
> search for configuration file in various paths, print paths if configuration is not found (#1993) (#2276)

- internal/core/webrtc_publish_index.html
> webrtc: optimize publish page for mobile devices (#2066)

- README.md
- apidocs/openapi.yaml
- internal/conf/path.go
- internal/core/path.go
- internal/record/agent.go
- internal/record/agent_test.go
- internal/record/part.go
- mediamtx.yml
> add runOnRecordSegmentCreate hook (#2451)

- internal/rpicamera/exe/camera.cpp
> rpi camera: fix Raspberry Pi Camera 3 auto focus (#2326)

- internal/conf/env/env.go
- internal/conf/env/env_test.go
> fix crash when setting deprecated settings with environment (#2529)

- apidocs/openapi.yaml
- internal/core/api.go
- internal/core/api_defs.go
- internal/core/api_test.go
> api: send error messages in response body (#2518)

- internal/core/api.go
- internal/core/api_test.go
> api: return empty list when page is empty (#2604)

- internal/staticsources/webrtc/source.go
> webrtc: allow using sourceFingerprint with WebRTC sources (#2618)

- internal/core/path_test.go
- internal/core/srt_conn.go
Illustrates solution 1 for #2654
> Add query as optional block for SRT publish and read

- internal/record/agent.go
- internal/record/agent_test.go
- internal/record/rec_format_fmp4_track.go
> record: fix invalid segment duration in case of offsets between video/audio (#2477)

- README.md
- internal/conf/path.go
- internal/core/path.go
- internal/core/path_test.go
- internal/core/static_source_handler.go
- internal/staticsources/hls/source.go
- internal/staticsources/hls/source_test.go
- internal/staticsources/rtmp/source.go
- internal/staticsources/rtmp/source_test.go
- internal/staticsources/rtsp/source.go
- internal/staticsources/rtsp/source_test.go
- internal/staticsources/srt/source.go
- internal/staticsources/srt/source_test.go
- internal/staticsources/udp/source.go
- internal/staticsources/udp/source_test.go
- internal/staticsources/webrtc/source.go
- internal/staticsources/webrtc/source_test.go
- mediamtx.yml
This allows to proxy requests to other servers by using regular expressions.
Fixes #824
> support static sources in paths with regular expressions (#824)

- internal/servers/webrtc/publish_index.html
- internal/servers/webrtc/read_index.html
> webrtc: support Chrome versions older than M72 (#2621)

- internal/servers/webrtc/publish_index.html
> webrtc: prevent NotReadableError when publishing with Android (#2698)

- apidocs/openapi.yaml
- internal/conf/conf_test.go
- internal/conf/env/env.go
- internal/conf/env/env_test.go
- internal/conf/path.go
- internal/core/path_manager.go
- internal/protocols/rpicamera/exe/camera.cpp
- internal/protocols/rpicamera/exe/parameters.c
- internal/protocols/rpicamera/exe/parameters.h
- internal/protocols/rpicamera/params.go
- internal/staticsources/rpicamera/source.go
- mediamtx.yml
> add rpiCameraAWBGains (#2858)

- internal/servers/hls/hlsjsdownloader/main.go
> fix compilation with Windows and git autocrlf (#3010)

- internal/protocols/webrtc/peer_connection.go
- internal/protocols/webrtc/peer_connection_test.go
- internal/protocols/webrtc/whip_client.go
> webrtc: fix deadlock when a WHEP source fails (#3062) (#3108)

- bench/proxy/Dockerfile
- bench/publish/Dockerfile
- bench/read/Dockerfile
> run go generate to download hls.min.js before run bench environment

- internal/servers/webrtc/publish_index.html
> webrtc: detect stereo tracks published with the web page (#2902)

- internal/protocols/webrtc/whip_client.go
Accept (optional) charsets.
Close: #3273
> fix(webrtc): Better Content-Type parsing

- internal/protocols/webrtc/outgoing_track.go
- internal/protocols/webrtc/peer_connection_test.go
- internal/servers/webrtc/server_test.go
- internal/servers/webrtc/session.go
> webrtc: support reading G711 16khz tracks (#2848)

- internal/servers/srt/server_test.go
- internal/staticsources/srt/source_test.go
- internal/staticsources/udp/source_test.go
for some reason, using "localhost" with UDP inside GitHub Actions and Docker stopped working.
> fix UDP-related tests

- README.md
- internal/conf/conf_test.go
- internal/conf/path.go
- mediamtx.yml
> enable runOnDemandRestart by default

- README.md
- internal/conf/conf_test.go
- internal/conf/path.go
- mediamtx.yml
This caused compatibility issues with existing instances.
> Revert "enable runOnDemandRestart by default (#3605)"

- Makefile
Bump to newest image version of same type for rpi
> Bump rpi binaries

- internal/servers/webrtc/read_index.html
> webrtc: fix 'duplicate payload type' error in read page (#3543)

- internal/servers/hls/index.html
> hls: fix delay when window is minimized (#3759)

- internal/protocols/webrtc/peer_connection.go
> webrtc: fix crash in case of congestion (#3813)

- README.md
- internal/core/metrics_test.go
- internal/core/path_test.go
- internal/core/test_on_demand/main.go
- internal/servers/rtsp/conn.go
- mediamtx.yml
> fix MTX_CONN_TYPE value with RTSP connections (#3967)

- README.md
- internal/api/api.go
- internal/playback/on_get.go
- internal/playback/on_list.go
- internal/playback/on_list_test.go
- internal/playback/segment_fmp4.go
- internal/recordcleaner/cleaner.go
- internal/recordstore/segment.go
- internal/recordstore/segment_test.go
> playback: allow filtering /list endpoint by start and end date (#3637) (#3489)

- internal/servers/srt/streamid.go
- internal/servers/srt/streamid_test.go
> srt: fix compatibility with Blackmagic Design hardware (#3701)

- internal/servers/webrtc/publisher.js
- internal/servers/webrtc/reader.js
> webrtc: fix reconnecting to server after a failure (#4022)

- internal/playback/on_list.go
- internal/playback/on_list_test.go
> fix extraneous playback list entry when start time specified

- internal/api/api.go
- internal/auth/manager.go
- internal/auth/manager_test.go
- internal/auth/request.go
- internal/defs/path.go
- internal/defs/path_access_request.go
- internal/metrics/metrics.go
- internal/playback/server.go
- internal/pprof/pprof.go
- internal/servers/hls/http_server.go
- internal/servers/hls/muxer.go
- internal/servers/hls/server_test.go
- internal/servers/rtmp/server_test.go
- internal/servers/rtsp/conn.go
- internal/servers/rtsp/server_test.go
- internal/servers/rtsp/session.go
- internal/servers/srt/conn.go
- internal/servers/srt/server_test.go
- internal/servers/webrtc/http_server.go
- internal/servers/webrtc/server_test.go
- internal/servers/webrtc/session.go
- internal/test/auth_manager.go
- internal/test/formats.go
- internal/test/logger.go
- internal/test/medias.go
- internal/test/path_manager.go
- internal/test/tls_cert.go
> webrtxc: fix MTX_QUERY not set when reading or publishing (#4138) (#3937)

- internal/recordstore/segment.go
> change from filepath.Walk to filepath.WalkDir in recordstore

- internal/conf/conf_test.go
- internal/conf/path.go
- internal/recordstore/path.go
- internal/recordstore/path_test.go
> restore support for using unix timestamp in record path (#4330)

- internal/servers/webrtc/publisher.js
- internal/servers/webrtc/reader.js
* add close() method
* move support functions into classes as static methods
* convert arrow functions into standard functions
* make most methods private
* add JSDocs
> webrtc: improve JavaScript classes

- internal/auth/jwt_claims.go
- internal/auth/manager.go
- internal/auth/manager_test.go
> support parsing JWT claims encoded as strings (#3696)

- README.md
- internal/restrictnetwork/restrict_network.go
- internal/staticsources/udp/source.go
- internal/staticsources/udp/source_test.go
>  support filtering interface and source IP in UDP sources (#4178)

- internal/auth/manager.go
> do not ask for credentials when authentication method is JWT (#4450)

- README.md
- internal/api/api.go
- internal/auth/credentials.go
- internal/auth/manager.go
- internal/auth/manager_test.go
- internal/auth/request.go
- internal/defs/path_access_request.go
- internal/metrics/metrics.go
- internal/playback/server.go
- internal/pprof/pprof.go
- internal/protocols/httpp/credentials.go
- internal/protocols/httpp/credentials_test.go
- internal/protocols/rtsp/credentials.go
- internal/protocols/rtsp/credentials_test.go
- internal/servers/hls/http_server.go
- internal/servers/hls/server_test.go
- internal/servers/rtmp/conn.go
- internal/servers/rtmp/server_test.go
- internal/servers/rtsp/conn.go
- internal/servers/rtsp/server_test.go
- internal/servers/rtsp/session.go
- internal/servers/srt/conn.go
- internal/servers/srt/server_test.go
- internal/servers/webrtc/http_server.go
- internal/servers/webrtc/server_test.go
- internal/servers/webrtc/session.go
- mediamtx.yml
This is safer than passing JWTs through query parameters, unfortunately support is limited.
> support passing JWTs through the password field

- internal/playback/muxer_fmp4.go
- internal/playback/muxer_mp4.go
- internal/playback/on_get.go
- internal/playback/on_get_test.go
- internal/playback/segment_fmp4.go
> playback: fix error 404 when seeking before start of segment (#4276) (#4533)

- internal/recorder/format_fmp4_track.go
consider all tracks when deciding the splitting point.
> recorder: improve fMP4 splitting algorithm

- README.md
- internal/recordstore/path.go
- internal/recordstore/path_test.go
- mediamtx.yml
> record: support storing timezone in recording segments (#3566)

- internal/core/core.go
- internal/core/metrics_test.go
- internal/core/path_test.go
- internal/protocols/rtmp/reader.go
- internal/protocols/rtmp/reader_test.go
- internal/servers/rtmp/conn.go
- internal/servers/rtmp/server.go
- internal/servers/rtmp/server_test.go
- internal/staticsources/rtmp/source.go
- internal/staticsources/rtmp/source_test.go
> rtmp: fix timeout when publishing with GLive T80 (#4002)

- go.mod
- go.sum
- internal/formatprocessor/klv.go
- internal/formatprocessor/klv_test.go
- internal/formatprocessor/processor.go
- internal/formatprocessor/processor_test.go
- internal/protocols/mpegts/from_stream.go
- internal/protocols/mpegts/to_stream.go
- internal/recorder/format_mpegts.go
- internal/unit/klv.go
> KLVA metadata handling

- internal/servers/webrtc/publish_index.html
- internal/servers/webrtc/read_index.html
> webrtc: fix endless loading in firefox

- README.md
- internal/core/metrics_test.go
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
> metrics: allow filtering metrics (#953)

- README.md
- api/openapi.yaml
- internal/conf/path.go
- internal/staticsources/handler.go
- internal/staticsources/rtp/source.go
- internal/staticsources/rtp/source_test.go
- internal/staticsources/rtp/udp.go
- internal/staticsources/rtp/unix.go
- mediamtx.yml
> support ingesting RTP streams (#1515)

- internal/protocols/httpp/server.go
Is this just redundant or am I missing something over here 😅?
> Remove redundant duplicated http middleware

- internal/protocols/webrtc/from_stream.go
- internal/protocols/webrtc/from_stream_test.go
Fixes #3878
Opus timestamp is now recomputed from scratch.
> webrtc: fix clippy audio when reading Opus (#3878)
