- client.go
- conf.go
- main.go
- path.go
- rtsp-simple-server.yml
This patch modifies the `runOnInit`/`runOnDemand`/`runOnPublish`/`runOnRead` callers to set an environment variable with the calling path. (For `runOnInit`, it will be called with the configured path, of course)
A `pathEnvVariable` configuration item is also introduced to specify the name of the environment variable to be used. Its default value is `RTSP_SERVER_PATH` and there is sanity checking to ensure that the provided name is valid (alphanumeric + underscore, no leading digit).
(Addresses #47)
> expose request path to runOn commands as an environment variable

- internal/confwatcher/confwatcher.go
- internal/confwatcher/confwatcher_test.go
improve config file watcher to support k8s configmap reloads
The config file watcher assumed a simple configuration where the
existing configuration file is overwritten by a text editor.
In practice this does not detect some more complex configuration change
scenarios such as :
* The configuration file is behind a symlink and the symlink is updated
* The configuration file is behind a double symlink (k8s configmap
update)
* The configuration file is not updated but removed the re-created
In order to fix these cases :
* Watch the configuration file parent directory instead of the file
itself, this lets us grab events event if the file was removed and a new
file is used.
* In addition to read/write event matching, watch for any change in
the configuration file path. This handles the symlink …
> improve config file watcher to support k8s configmap reloads

- internal/conf/conf.go
- internal/metrics/metrics.go
- main.go
- rtsp-simple-server.yml
Port could be specified by using either `metricsPort` config file entry or `RTSP_METRICSPORT` environment variable.
> add ability to configure metrics port

- README.md
Nowadays `gst-play-1.0` hides away the complexity of the pipeline. We only need to pass a valid URI to it.
> README: Simplify GStreamer stream playback command

- README.md
Added 'location' parameter to rtspsrc element in example in 'TCP transport' section
> Fixed example with GStreamer usage in README

- Makefile
Docker >= 20.10.0 has a new flag that allows to pull images of a
specific architecture; i.e:
docker pull --platform=linux/arm/v8 aler9/rtsp-simple-server:0.0.0
Image tags like "0.0.0-arm64" allowed to pull images of a specific
architecture before the introduction of the flag, and are not necessary
anymore.
> Stop generating architecture-specific docker tags

- .dockerignore
- Makefile
- README.md
- apidocs/openapi.yaml
- internal/conf/env_test.go
- internal/conf/path.go
- internal/core/api.go
- internal/core/hls_source.go
- internal/core/path.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_source.go
- internal/core/rtsp_source.go
- internal/core/source_static.go
- internal/rpicamera/embeddedexe.go
- internal/rpicamera/exe/Makefile
- internal/rpicamera/exe/camera.cpp
- internal/rpicamera/exe/camera.h
- internal/rpicamera/exe/encoder.c
- internal/rpicamera/exe/encoder.h
- internal/rpicamera/exe/main.c
- internal/rpicamera/exe/parameters.c
- internal/rpicamera/exe/parameters.h
- internal/rpicamera/params.go
- internal/rpicamera/pipe.go
- internal/rpicamera/rpicamera.go
- internal/rpicamera/rpicamera_disabled.go
- rtsp-simple-server.yml
> Add native support for the Raspberry Pi camera

- go.mod
- go.sum
- internal/core/data.go
- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/hls_source_test.go
- internal/core/reader.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_source.go
- internal/core/rtsp_session.go
- internal/core/rtsp_source.go
- internal/core/rtsp_source_test.go
- internal/core/stream.go
- internal/core/streamtrack.go
- internal/core/streamtrack_generic.go
- internal/core/streamtrack_h264.go
- internal/core/streamtrack_mpeg4audio.go
- internal/hls/muxer_variant_fmp4_segmenter.go
> Decode streams once and only when needed

- README.md
- apidocs/openapi.yaml
- go.mod
- go.sum
- internal/core/api_test.go
- internal/core/hls_muxer.go
- internal/core/hls_server.go
- internal/core/metrics.go
- internal/core/metrics_test.go
- internal/core/path.go
- internal/core/rtmp_server.go
- internal/core/rtsp_server.go
- internal/core/rtsp_session.go
- internal/core/stream.go
- internal/core/streamtrack_h264.go
- internal/core/streamtrack_mpeg4audio.go
- internal/rtmp/bytecounter/reader.go
- internal/rtmp/bytecounter/reader_test.go
- internal/rtmp/bytecounter/writer.go
- internal/rtmp/bytecounter/writer_test.go
- internal/rtmp/conn.go
- internal/rtmp/conn_test.go
- internal/rtmp/rawmessage/reader.go
- internal/rtmp/rawmessage/reader_test.go
- internal/rtmp/rawmessage/writer.go
> api, metrics: add number of bytes received and sent from/to all entities

- internal/core/data.go
- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_source.go
- internal/core/rtsp_session.go
- internal/core/rtsp_source.go
- internal/core/stream.go
- internal/hls/muxer.go
- internal/hls/muxer_variant.go
- internal/hls/muxer_variant_fmp4.go
- internal/hls/muxer_variant_fmp4_segmenter.go
- internal/hls/muxer_variant_mpegts.go
- internal/hls/muxer_variant_mpegts_segmenter.go
* add a NTP timestamp field to each data unit
* use that NTP timestamp in all protocols
> produce same absolute time in RTSP and HLS

- README.md
- go.mod
- go.sum
- internal/core/formatprocessor_h264.go
- internal/core/formatprocessor_h265.go
- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_source.go
- internal/core/webrtc_conn.go
- internal/hls/fmp4/init_track.go
- internal/hls/mpegts/writer.go
- internal/hls/muxer.go
- internal/hls/muxer_primary_playlist.go
- internal/hls/muxer_test.go
- internal/hls/muxer_variant.go
- internal/hls/muxer_variant_fmp4.go
- internal/hls/muxer_variant_fmp4_part.go
- internal/hls/muxer_variant_fmp4_playlist.go
- internal/hls/muxer_variant_fmp4_segment.go
- internal/hls/muxer_variant_fmp4_segmenter.go
- internal/hls/muxer_variant_mpegts.go
- internal/hls/muxer_variant_mpegts_segmenter.go
> support reading H265 tracks with HLS

- internal/hls/muxer_test.go
- internal/hls/muxer_variant_fmp4_segmenter.go
this happened when variant is lowLatency and two AUs have adjacent DTSs, resulting in a sample duration equal to zero.
discovered while investigating #1156
> hls muxer: fix crash

- internal/rtmp/conn.go
- internal/rtmp/conn_test.go
> rtmp server: fix compatibility with Neko

- internal/core/rtmp_server_test.go
- internal/core/rtsp_server.go
- internal/core/rtsp_server_test.go
> rtsp server: make runOnConnect work again

- internal/rpicamera/exe/camera.cpp
- internal/rpicamera/exe/parameters.c
Fixes #1296 
In order to read a video frame from libcamera, the read operation has to be requested by using a request.
Each request contains a buffer:
```
request1
- buffer1
request2
- buffer2
request3
- buffer3
```
When `rpiCameraMode` is set, two video streams are initiated, a main one and a secondary one with a greater definition:
```
[0:03:30.432024088] [1253]  INFO Camera camera.cpp:1028 configuring streams: (0) 1920x1080-YUV420 (1) 3840x2160-SRGGB10_CSI2P
```
In this case, each request must contain two buffers in order to read frames from both video streams, even if one of them is not used:
```
request1
- buffer1a
- buffer1b
request2
- buffer2a
- buffer2b
request3
- buffer3a
- buffer3b
```
If the second buffer is not present, libcamera silently creates a buffer during each read …
> rpicamera: fix low framerate when rpiCameraMode is set (#1296)

- internal/core/webrtc_conn.go
Fixes #1482
OnConnectionStateChange of pion/webrtc is not thread safe. Add a mutex to make it thread safe.
> webrtc: fix crash during client disconnection (#1482)

- apidocs/openapi.yaml
Fixes #1486 to change the api schema to the correct number type to avoid unexpected behaviour.
> Update OpenAPI schema to use 'integer' data type for input parameter

- internal/rtmp/conn.go
- internal/rtmp/conn_test.go
> rtmp: fix panic when publishing audio-only streams (#1459)

- internal/conf/conf_test.go
- internal/conf/path.go
- internal/core/core.go
- internal/rpicamera/libcamera.go
- internal/rpicamera/libcamera_disabled.go
- internal/rpicamera/rpicamera.go
> rpicamera: support two CSI cameras at once (#1573)

- README.md
- go.mod
- internal/conf/path.go
- internal/core/hls_source.go
- internal/core/path.go
- internal/core/source_static.go
- internal/core/udp_source.go
- rtsp-simple-server.yml
Fixes #1481 
[rtsp-simple-server_v0.21.6-5-ga45313b_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/10971934/rtsp-simple-server_v0.21.6-5-ga45313b_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.21.6-5-ga45313b_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/10971936/rtsp-simple-server_v0.21.6-5-ga45313b_linux_amd64.tar.gz)
[rtsp-simple-server_v0.21.6-5-ga45313b_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/10971939/rtsp-simple-server_v0.21.6-5-ga45313b_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.21.6-5-ga45313b_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/10971941/rtsp-simple-server_v0.21.6-5-ga45313b_linux_armv6.tar.gz)
[rtsp-simple-server_v0.21.6-5-ga45313b_linux_armv7.tar.gz](https://github.com …
> support reading UDP/MPEG-TS streams

- internal/rpicamera/rpicamera.go
> rpi camera: support running on 32-bit OS with 64-bit kernel (#1644)

- internal/conf/conf.go
Fixes #1702 
this happened when udpMaxPayloadSize was not explicitly set in configuration file.
> fix corrupted packets when udpMaxPayloadSize is not set (#1702)

- internal/core/metrics.go
In commit 3475762 from PR #1678 the restrictNetwork function was called twice for the metrics listening address only, which leads to 0.0.0.0 listeners not working properly for the metrics server.
> fix: metrics listener address sanitization

- apidocs/openapi.yaml
- internal/conf/path.go
- internal/conf/rtsprangetype.go
- internal/core/rtsp_source.go
- internal/core/rtsp_source_test.go
- mediamtx.yml
Send `Range` RTSP header when source is RTSP and configuration options `rtspRangeType` & `rtspRangeStart` are configured.
> Support RTSP configurable Range header

- internal/core/webrtc_publish_index.html
- internal/core/webrtc_read_index.html
- mediamtx.yml
this fixes a regression introduced in v0.23.0.
Fixes #1817
> webrtc: fix exception in browser when webrtcICEServers is empty (#1817)

- README.md
- internal/rtmp/tracks/read.go
- internal/rtmp/tracks/read_test.go
this fixes a regression introduced in v0.23.0.
Fixes #1819
> rtmp: fix crash when publishing video-only tracks (#1819)

- apidocs/openapi.yaml
- internal/core/api.go
- internal/core/api_defs.go
- internal/core/api_test.go
- internal/core/core_test.go
- internal/core/hls_manager.go
- internal/core/hls_muxer.go
- internal/core/metrics.go
- internal/core/path.go
- internal/core/path_manager.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_server.go
- internal/core/rtsp_conn.go
- internal/core/rtsp_server.go
- internal/core/rtsp_session.go
- internal/core/webrtc_manager.go
- internal/core/webrtc_session.go
> api: add /get endpoints (#1577)

- internal/core/webrtc_http_server.go
Add the `access-control-expose-headers: E-Tag` header to the `/whep` response to allow access to the `E-Tag` header when making a cross-origin request.
> Expose E-Tag header for cross-origin WHEP requests

- internal/core/webrtc_http_server.go
- internal/core/webrtc_manager_test.go
- internal/core/webrtc_publish_index.html
- internal/core/webrtc_read_index.html
- internal/core/webrtc_session.go
offers and answers are now encoded in SDP in place of JSON; Location header is set by the server.
This fixes compatibility with GStreamer and whipsink.
> webrtc: fix WHIP/WHEP implementation (#1857)

- internal/externalcmd/cmd.go
- internal/externalcmd/cmd_unix.go
- internal/externalcmd/cmd_win.go
on Windows, when using cmd.exe or a bat file as external command.
> allow using special characters in external commands (#1652)

- apidocs/openapi.yaml
- internal/conf/path.go
- internal/rpicamera/exe/camera.cpp
- internal/rpicamera/exe/parameters.c
- internal/rpicamera/exe/parameters.h
- internal/rpicamera/params.go
> rpi camera: allow using decimal FPS (#1743)

- internal/core/webrtc_http_server.go
- internal/core/webrtc_manager_test.go
Hello, 
We plan to use Mediamtx for streaming WebRTC video / audio from local recorders like Dahua, but during testing we have found one issue - there is no information about internal WebRTC stream id in /whep request / response flow, so we don't have any information about stream that was created and cannot use Mediamtx HTTP API to list current WebRTC connections and find a stream that we just created.
So, I have a proposal to add this WebRTC stream id to /whep response headers, that will help to set info about current created stream and then manage it using Mediamtx HTTP API.
Best regards, 
Victor
> Add WebRTC stream id to whep response headers

- go.mod
- go.sum
- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/rtmp_conn.go
- internal/core/udp_source.go
- internal/core/webrtc_outgoing_track.go
- internal/formatprocessor/av1.go
- internal/formatprocessor/h264.go
- internal/formatprocessor/h264_test.go
- internal/formatprocessor/h265.go
- internal/formatprocessor/h265_test.go
- internal/formatprocessor/mpeg2audio.go
- internal/formatprocessor/mpeg4audio_generic.go
- internal/formatprocessor/mpeg4audio_latm.go
- internal/formatprocessor/opus.go
- internal/formatprocessor/processor.go
- internal/formatprocessor/vp9.go
- internal/rtmp/tracks/write.go
> support reading MP4A-LATM-encoded AAC with RTMP and HLS (#1694)

- internal/core/api.go
- internal/core/api_test.go
> api: fix setting default parameters when creating a path (#1853)

- internal/core/core.go
- internal/core/hls_http_server.go
- internal/core/hls_manager_test.go
- internal/core/webrtc_http_server.go
- internal/core/webrtc_manager_test.go
> webrtc: make preflight OPTIONS requests work with external auth (#1941)

- apidocs/openapi.yaml
- internal/core/api_defs.go
- internal/core/api_test.go
- internal/core/rtmp_conn.go
- internal/core/rtsp_session.go
- internal/core/webrtc_session.go
Hello Alessandro,
Thanks for your great work! I have a project in mind where I need to create a webpage displaying a list of all active RTMP broadcasts, along with links to their corresponding WebRTC streams. Currently, I am using the /v2/rtmpconns/list endpoint to fetch all the RTMP streams and filter them based on their status. However, I am facing an issue as the path field is missing, and without it, I cannot construct the link to the WebRTC stream.
Hope this functionality will be useful for others too. Looking forward for your comments/remarks
> api: add path to RTMP connections, RTSP sessions, WebRTC sessions (#1962)

- internal/core/api.go
- internal/core/api_test.go
Getting path information for nested paths always fails and gives a 404. This PR fixes this problem
> Fix: API v2/paths/get with nested path always results in 404

- apidocs/openapi.yaml
- internal/core/api.go
this involves /v2/config/paths/edit and /v2/config/paths/remove
> api: return 404 when a path configuration is not found (#2067)

- internal/rpicamera/exe/camera.cpp
not sure if this is backward compatible with older version of libcamera, but there was an API change in recnet libcamera
see https://github.com/raspberrypi/libcamera/commit/26a4b83d1b9443795dbcb21fa6c23117f113216a
> fix a compile error with recent libcamera

- README.md
- apidocs/openapi.yaml
- go.mod
- go.sum
- internal/conf/conf.go
- internal/conf/path.go
- internal/core/api.go
- internal/core/api_defs.go
- internal/core/api_test.go
- internal/core/authentication.go
- internal/core/core.go
- internal/core/hls_source_test.go
- internal/core/rtmp_conn.go
- internal/core/source_static.go
- internal/core/srt_conn.go
- internal/core/srt_listener.go
- internal/core/srt_server.go
- internal/core/srt_server_test.go
- internal/core/srt_source.go
- internal/core/srt_source_test.go
- internal/core/webrtc_manager.go
- mediamtx.yml
Fixes #563
publish:
```
srt://localhost:8890?streamid=publish:path_name:user:pass&pkt_size=1316
```
read:
```
srt://localhost:8890?streamid=read:path_name:user:pass
```
proxy:
```yml
paths:
mystream:
source: srt://ip-of-camera:port?pkt_size=1316
```
> support publishing, reading, proxying with SRT

- .github/workflows/binaries.yml
This uses workflow_dispatch, so it won't run unless triggered manually.
It could be useful for people who fork the repo.
> Create GitHub action to build binaries

- internal/formatprocessor/vp8.go
- internal/formatprocessor/vp9.go
avoid printing 'received a non-starting fragment without any previous starting fragment'
> remove warning when decoding VP8 or VP9

- internal/core/hls_index.html
- internal/core/webrtc_read_index.html
This adds support for specifying controls, autoplay, muted, and playsinline via query strings.
Example:
`?controls=0&muted=0`
The default values remain unchanged, but this allows the user to specify them.
> Add video player options via query string.

- internal/rtmp/message/extended_sequence_start.go
- internal/rtmp/reader.go
- internal/rtmp/reader_test.go
Prior to this change, when trying to stream AV1 over enhanced RTMP using XSplit Broadcaster, the server was refusing the content with "unsupported video codec: av01" message.
> allow RTMP streaming with codecid=av01 or hvc1

- README.md
- apidocs/openapi.yaml
- go.mod
- go.sum
- internal/conf/conf.go
- internal/conf/path.go
- internal/core/core.go
- internal/core/path.go
- internal/core/path_manager.go
- internal/core/srt_conn.go
- internal/core/webrtc_outgoing_track.go
- internal/record/agent.go
- internal/record/agent_test.go
- internal/record/cleaner.go
- internal/record/cleaner_test.go
- internal/record/part.go
- internal/record/record.go
- internal/record/record_path.go
- internal/record/recorder.go
- internal/record/segment.go
- internal/record/track.go
- internal/stream/stream.go
- mediamtx.yml
Fixes #1399
* <s>[ ] support VP8 tracks</s>
<s>* [ ] support M-JPEG tracks</s>
<s>* [ ] support G722 tracks</s>
<s>* [ ] support G711 tracks</s>
<s>* [ ] support LPCM tracks </s>
The recording format is fMP4, since it satisfies most requirements:
* it is fault tolerant
* it can be read by most players and browsers
All parameters are in the configuration file:
```yml
record: no
recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S
recordFormat: fmp4
recordPartDuration: 100ms
recordSegmentDuration: 1h
recordDeleteAfter: 24h
```
[mediamtx_v1.0.0-33-g2bfdc21_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12448708/mediamtx_v1.0.0-33-g2bfdc21_darwin_amd64.tar.gz)
[mediamtx_v1.0.0-33-g2bfdc21_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12448709/mediamtx_v1.0.0- …
> implement native recording (#1399)

- README.md
- apidocs/openapi.yaml
- internal/core/api_defs.go
- internal/core/conn.go
- internal/core/hls_muxer.go
- internal/core/hls_source.go
- internal/core/path.go
- internal/core/reader.go
- internal/core/rpicamera_source.go
- internal/core/rtmp_conn.go
- internal/core/rtmp_source.go
- internal/core/rtsp_conn.go
- internal/core/rtsp_server.go
- internal/core/rtsp_session.go
- internal/core/rtsp_source.go
- internal/core/source.go
- internal/core/source_redirect.go
- internal/core/source_static.go
- internal/core/srt_conn.go
- internal/core/srt_source.go
- internal/core/udp_source.go
- internal/core/webrtc_session.go
- internal/core/webrtc_source.go
- mediamtx.yml
Fixes #1414 
new variables: MTX_CONN_TYPE, MTX_CONN_ID, MTX_SOURCE_TYPE, MTX_SOURCE_ID, MTX_READER_TYPE, MTX_READ_ID
> add additional environment variables to custom commands (#1414)

- internal/conf/conf.go
- internal/conf/conf_test.go
- internal/conf/path.go
rtmpServerKey, rtmpServerCert, recordPath, rpiCameraExposure, rpiCameraAWB, rpiCameraDenoise, rpiCameraMetering, rpiCameraAfMode, rpiCameraAfRange, rpiCameraAfSpeed were not set correctly when missing in the configuration file.
> fix default value of some settings

- internal/formatprocessor/h264_test.go
- internal/formatprocessor/h265.go
- internal/formatprocessor/h265_test.go
> fix crash when processing H265 (#2378)

- internal/core/webrtc_http_server.go
- internal/core/webrtc_publish_index.html
- internal/core/webrtc_read_index.html
- internal/core/webrtc_source_test.go
- internal/whip/post_offer.go
> webrtc: fix ETag header name according to specification (#2396)

- go.mod
- go.sum
- internal/rtmp/reader.go
> rtmp: fix compatibility issue with some DJI drones (#2375)

- internal/core/rtmp_conn.go
- internal/core/srt_conn.go
I fixed the issue I opened https://github.com/bluenviron/mediamtx/issues/2430
There was a variable name issue in the nil checks. Probably a typo. Please merge
> api: fix crash when retrieving RTMP and SRT connections (#2430)

- internal/conf/path.go
- internal/core/path.go
- internal/core/path_manager.go
- internal/core/path_test.go
- internal/record/agent.go
- internal/record/part.go
- internal/record/segment.go
> allow to start/stop recording without disconnecting clients (#2395)

- README.md
- apidocs/openapi.yaml
- internal/conf/path.go
- internal/core/path.go
- internal/record/agent.go
- internal/record/agent_test.go
- internal/record/cleaner.go
- internal/record/segment.go
- mediamtx.yml
> add runOnRecordSegmentComplete and rclone integration (#2404)

- internal/core/webrtc_http_server.go
The [suggested WHEP reference client](https://github.com/bluenviron/mediamtx/issues/2424#issuecomment-1736839160) is not able to access the `Location` header at:
https://github.com/medooze/whip-whep-js/blob/v1.0.3/whep.js#L86-L87
This PR allows the browser to expose that header to the javascript code.
PS: It [also needs to use the `DELETE` method](https://github.com/medooze/whip-whep-js/blob/v1.0.3/whep.js#L481-L485). should I add it to this PR too? or another PR?
Though, this is still not enough to get that client working, as it fails with:
```
2023/10/03 20:52:30 DEB [WebRTC] [conn [::1]:44266] PATCH /camera_sub/whep
2023/10/03 20:52:30 DEB [WebRTC] [conn [::1]:44266] [c->s] PATCH /camera_sub/whep HTTP/1.1
Host: localhost:8889
Accept: */*
Accept-Encoding: gzip, deflate, br …
```
> webrtc: expose the location header

- internal/core/webrtc_manager.go
- internal/core/webrtc_publish_index.html
- internal/core/webrtc_read_index.html
> webrtc: fix reading Opus stereo tracks with Chrome (#2043)

- internal/core/webrtc_http_server.go
The link header was getting ignored by browser fetch as it was not exposed by Access-Control-Expose-Headers
fixes #2480
> fix(webrtc): expose ice servers on cors requests

- README.md
- go.mod
- go.sum
- internal/core/authentication.go
- internal/core/hls_http_server.go
- internal/core/hls_muxer.go
- internal/core/mpegts.go
- internal/core/path.go
- internal/core/path_manager.go
- internal/core/path_test.go
- internal/core/publisher.go
- internal/core/reader.go
- internal/core/rtmp_conn.go
- internal/core/rtsp_conn.go
- internal/core/rtsp_session.go
- internal/core/source.go
- internal/core/srt_conn.go
- internal/core/webrtc_http_server.go
- internal/core/webrtc_session.go
- mediamtx.yml
> add environment variable MTX_QUERY to some hooks (#2483)

- internal/core/api_test.go
- internal/core/path_test.go
- internal/core/webrtc_http_server.go
- internal/core/webrtc_manager.go
- internal/core/webrtc_manager_test.go
- internal/core/webrtc_publish_index.html
- internal/core/webrtc_read_index.html
- internal/core/webrtc_source.go
- internal/whip/delete_session.go
- internal/whip/options_ice_servers.go
- internal/whip/patch_candidate.go
- internal/whip/post_offer.go
- internal/whip/whip.go
this actually does nothing more than returning OK to satisfy the [whep.js `DELETE` method](https://github.com/medooze/whip-whep-js/blob/v1.0.3/whep.js#L481-L485) as mentioned in https://github.com/bluenviron/mediamtx/pull/2453.
> webrtc: implement the whep http delete method

- internal/core/path.go
- internal/httpserv/wrapped_server_test.go
- internal/record/agent.go
- internal/record/agent_instance.go
- internal/record/agent_test.go
- internal/record/rec_format.go
- internal/record/rec_format_fmp4.go
- internal/record/rec_format_fmp4_part.go
- internal/record/rec_format_fmp4_segment.go
- internal/record/rec_format_fmp4_track.go
- internal/record/rec_format_mpegts.go
- internal/record/rec_format_mpegts_segment.go
> restart recordings in case of errors (#2439)

- apidocs/openapi.yaml
- internal/core/api.go
- internal/core/api_test.go
- internal/core/hls_manager.go
- internal/core/path_manager.go
- internal/core/rtmp_server.go
- internal/core/rtsp_server.go
- internal/core/srt_server.go
- internal/core/webrtc_manager.go
This is needed to differentiate between calls to non-existent andpoints and calls to valid endpoints, but with an ID pointing to a non-existing item, and to return JSON in the latter case.
> api: return 500 instead of 404 in case of non-existing items

- internal/confwatcher/confwatcher.go
The current behavior of performing "evalSymlinks" on the "watchedPath" seems to lead to mismatches and ignored changes if the event-reported "eventPath" is not similarly processed on Windows.
> fix hot reloading on Windows when letter case changes (#2585)

- internal/core/webrtc_http_server.go
> webrtc: fix crash in case of errors during PATCH (#2609)

- internal/core/webrtc_publish_index.html
Ciao,
For my personal needs, I wanted to add the audio capture feature, but I ended up adding other features, namely (#1837) (#2167).
I added these new options:
- video width
- video height
- video ideal framerate
- audio capture
And I implemented the feature to store the options in the URL.
I also did a bit of refactoring:
- Improve alignment of the form
- Reduce redundancy of `document.getElementById` for the different inputs in the form
- Use only once `new URL(window.location.href)`
> webrtc: add options (width, height, framerate, audio capture) and store parameters in URL (#1837) (#2167)

- internal/core/hls_index.html
I propose the following changes to the HLS.js:
- BUGFIX: pass "video" element to create() on restart triggering fatal-error
- STABILITY: await MEDIA_ATTACHED event before performing "loadSource" on HLS
- STABILITY: await MANIFEST_PARSED event before performing "play" on video element
- RESILIENCE: on "MEDIA_ERROR" event perform "recoverMediaError" on HLS
> HLS.js usage: bugfix, stability improvements and resilience improvement

- README.md
- internal/core/path.go
- mediamtx.yml
> fix crash when publishing to a path with 'runOnDemand' from outside 'runOnDemand' (#2636)

- README.md
- apidocs/openapi.yaml
- internal/core/api_test.go
- internal/core/core.go
- internal/core/metrics.go
- internal/core/metrics_test.go
- internal/core/path.go
- internal/core/srt_server.go
- internal/defs/api.go
- internal/stream/stream.go
- internal/stream/stream_format.go
The following tries to resolve issues https://github.com/bluenviron/mediamtx/issues/2620 and https://github.com/bluenviron/mediamtx/issues/2619 by adding the following, missing Prometheus exports: paths_bytes_sent, srt_conns, srt_conns_bytes_received, srt_conns_bytes_sent
Fixes #2620 
Fixes #2619
> add missing Prometheus exports (#2620, #2619): paths_bytes_sent, srt_conns, srt_conns_bytes_received, srt_conns_bytes_sent 

- internal/core/core.go
> fix setting 'recordDeleteAfter' to zero (#2670)

- internal/core/webrtc_http_server.go
- internal/core/webrtc_manager_test.go
> webrtc: fix crash when reading from path 'publish' (#2688)

- internal/conf/conf_test.go
- internal/conf/env/env_test.go
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
> test: use `t.Setenv` to set env vars in tests

- internal/protocols/mpegts/to_stream.go
- internal/protocols/webrtc/incoming_track.go
- internal/staticsources/hls/source.go
> webrtc: fix bad quality when converting Opus from WebRTC to LL-HLS (#2499)

- README.md
- internal/record/record_path.go
- internal/record/record_path_test.go
- mediamtx.yml
While parsing %s (unix timestamp) takes precedence over Y-%m-%d_%H-%M-%S
> support unix timestamp in filenames of recorded segments

- internal/externalcmd/cmd.go
The RunOn{Init,Ready, etc} commands call back with a generic 'exited with code 0' message if the command is specified with its relevant 'Restart' option set to 'yes'. eg
`runOnInit command exited: command exited with code 0`
This PR allows underlying `err` result to actually be seen in logs, eg
`runOnInit command exited: exec: "ffmpeg": executable file not found in %PATH%`
> RunOn.. commands - Propagate errors in restart configurations

- internal/servers/hls/http_server.go
- internal/servers/rtmp/conn.go
- internal/servers/rtsp/conn.go
- internal/servers/srt/conn.go
- internal/servers/webrtc/http_server.go
- internal/servers/webrtc/server.go
- internal/servers/webrtc/session.go
this allows to mitigate brute force attacks and is possible thanks to https://github.com/datarhei/gosrt/pull/43
> srt: wait some seconds before returning authentication errors

- internal/servers/srt/conn.go
- internal/servers/srt/streamid.go
- internal/servers/srt/streamid_test.go
> srt: support standard streamID syntax (#2469)

- internal/servers/hls/index.html
when a player received a stream with incompatible codecs, it started polling the server for index.m3u8 in an infinite loop. This was caused by #2631
> hls: fix infinite loop in web client when reading incompatible codecs

- internal/externalcmd/cmd.go
Expand environment vars from the underlying host in the command.
The specific usecase this will solve for us is publishing the hostname to an etcd store on ready which will allow naive horizontal scalability.
> Expand host env vars

- go.mod
- internal/externalcmd/cmd.go
- internal/externalcmd/cmd_unix.go
- internal/externalcmd/cmd_win.go
> when stopping hooks, stop all their subprocesses too (#3004)

- scripts/run.mk
Follow-up on this issue comment:
https://github.com/bluenviron/mediamtx/issues/3097#issuecomment-1977747645
> Correction for missing `go generate` in `run` makefile

- internal/protocols/webrtc/whip_client.go
- internal/staticsources/webrtc/source.go
Tentative fix for #3118
It still leaks, but less; Here is what remains leaking:
```
goroutine profile: total 128
50 @ 0x100843218 0x10083cae8 0x100876730 0x1008b8538 0x1008b9880 0x1008b9871 0x100a20cb8 0x100a32234 0x100b5ddd0 0x100ac7488 0x100ac75f0 0x100b5ed58 0x10087d084
#	0x10087672f	internal/poll.runtime_pollWait+0x9f		/opt/homebrew/opt/go/libexec/src/runtime/netpoll.go:345
#	0x1008b8537	internal/poll.(*pollDesc).wait+0x27		/opt/homebrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:84
#	0x1008b987f	internal/poll.(*pollDesc).waitRead+0x1ff	/opt/homebrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:89
#	0x1008b9870	internal/poll.(*FD).Read+0x1f0			/opt/homebrew/opt/go/libexec/src/internal/poll/fd_unix.go:164
#	0x100a20cb7	net.(*netFD).Read+0x27 …
```
> fix: whep gathering failure leaks peer connections

- internal/servers/hls/muxer_instance.go
- internal/servers/hls/server_test.go
>  hls: fix directory creation when using hlsDirectory (#3135)

- README.md
- apidocs/openapi.yaml
- internal/conf/webrtc_ice_server.go
- internal/servers/webrtc/http_server.go
- internal/servers/webrtc/server.go
- internal/servers/webrtc/server_test.go
- internal/servers/webrtc/session.go
- mediamtx.yml
Fixes #3145 
The config update will not change the default behaviour.  It does however allow the asymmetric model.  This is how LiveKit uses TURN servers for example.
> Add option for ICE servers to be client only

- internal/playback/fmp4.go
- internal/playback/on_get.go
- internal/playback/on_get_test.go
- internal/playback/on_list.go
the duration of segments was computed erroneously, since it was taking into consideration the last track only. Now the duration of a segment corresponds to the maximum duration among all tracks.
> playback: fix concatenation of segments with multiple tracks

- apidocs/openapi.yaml
- internal/api/api.go
- internal/api/record.go
- internal/conf/conf_test.go
- internal/conf/path.go
- internal/playback/on_get_test.go
- internal/playback/on_list.go
- internal/playback/on_list_test.go
- internal/playback/segment.go
- mediamtx.yml
this has become useless after the introduction of the new authentication system, that already allows to select which paths are available for playback
> deprecate path.playback parameter

- internal/core/path.go
- internal/core/static_source_handler.go
> api: fix crash when changing settings of an on-demand source that is idle (#3246)

- internal/servers/hls/http_server.go
- internal/servers/hls/muxer.go
- internal/servers/hls/server.go
...
runOnDemand:
...
The comments in the configuration file say that MTX_QUERY is available, but in fact, it is empty when the HLS stream is requested.
I passed the query from the hls/http_server to the muxer.
> fix when runOnDemand for HLS, variable MTX_QUERY is empty.

- apidocs/openapi.yaml
- internal/api/api.go
- internal/conf/conf.go
- internal/core/core.go
- internal/metrics/metrics.go
- internal/playback/server.go
- internal/pprof/pprof.go
- internal/protocols/httpp/wrapped_server.go
- internal/protocols/httpp/wrapped_server_test.go
- internal/servers/hls/http_server.go
- internal/servers/hls/server.go
- internal/servers/webrtc/http_server.go
- mediamtx.yml
Fixes #2491
Fixes #3235
Replaces #2658
> support HTTPS, Allow-Origin and trusted proxies in API, playback server, metrics server and pprof server (#2658) (#2491) (#3235)

- internal/protocols/rtmp/reader.go
some rtmp client will send set chunk size after publishing stream, which causes the metadata to fail to be read.
I add code to skip set chunk size message in readTracks() in rtmp/reader.go.
> fix rtmp server miss the opportunity to read metadata when clients send set chunk size message after publishing stream.

- internal/conf/auth_internal_users.go
- internal/conf/conf.go
- internal/conf/conf_test.go
- internal/conf/path.go
- internal/conf/webrtc_ice_server.go
when some subfields of authInternalUsers and authHTTPExclude were not set explicitly in the configuration file, default values were used in their place. This is caused by a strange behavior of Go (https://github.com/golang/go/issues/21092)
> fix unexpected behavior of authInternalUsers or authHTTPExclude

- apidocs/openapi.yaml
- internal/conf/conf.go
- internal/core/core.go
- internal/servers/hls/muxer.go
- internal/servers/hls/server.go
- mediamtx.yml
"closeAfterInactivity"  was dead code fixed at 60 seconds, indicates the muxer will be closed when there is no readers request and this amount of time has passed.
This PR adds "hlsMuxerCloseAfter" in mediamtx.yml to do the same thing.
> HLS: make closeAfterInactivity configurable

- go.mod
- go.sum
- internal/auth/manager.go
- internal/auth/manager_test.go
- internal/conf/conf.go
- internal/conf/rtsp_auth_methods.go
- internal/servers/rtsp/conn.go
- internal/servers/rtsp/server.go
- internal/servers/rtsp/server_test.go
> rtsp: fix authentication when algorithm field is not supported (#3116)

- internal/api/api_test.go
- internal/conf/conf.go
Don't return a 404 error if the path doesn't exist yet
Fixes https://github.com/bluenviron/mediamtx/issues/3361
> api: make replace paths idempotent

- internal/protocols/webrtc/incoming_track.go
- internal/protocols/webrtc/outgoing_track.go
- internal/protocols/webrtc/peer_connection.go
- internal/protocols/webrtc/peer_connection_test.go
- internal/servers/webrtc/read_index.html
- internal/servers/webrtc/session.go
Fixes #3371
TODO
* <s>[ ] fix "frame is too big error" (inside RTP Opus encoder)</s>
> webrtc: support reading and proxying multichannel Opus (#3371)

- internal/protocols/webrtc/peer_connection.go
- internal/protocols/webrtc/peer_connection_test.go
> webrtc: fix error "Failed to setup RTCP mux" on some readers (#3381)

- internal/protocols/rtmp/reader.go
- internal/protocols/rtmp/reader_test.go
current main branch.
when I publish an aac file by ffmpeg to `mediamtx`, I met an error.
> 2024/06/01 17:10:55 INF [RTMP] [conn [::1]:57689] closed: not enough bits
The root cause is the `mediamtx` want to parse an audio message with empty payload.
1. start the server: `./mediamtx`
2. publish an aac file with ffmpeg: `ffmpeg -stream_loop -1 -re -i music.aac -c copy -f flv -y rtmp://localhost/live/test`
3. check the `mediamtx` log: `INF [RTMP] [conn [::1]:57689] closed: not enough bits`
and `ffmpeg` cmd exit with error.
yes 
<details>
<summary>MediaMTX logs</summary>
```
2024/06/01 17:10:53 INF MediaMTX v0.0.0
2024/06/01 17:10:53 INF configuration loaded from /Users/jacobsu/hack/media/mediamtx/mediamtx.yml
2024/06/01 17:10:53 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), …
```
> fix single aac file rtmp publish error.

- README.md
- internal/core/path.go
- internal/core/path_test.go
- internal/record/agent.go
- internal/record/agent_instance.go
- internal/record/agent_test.go
- internal/record/format_fmp4.go
- internal/record/format_fmp4_part.go
- internal/record/format_fmp4_segment.go
- internal/record/format_fmp4_track.go
- internal/record/format_mpegts.go
- internal/record/format_mpegts_segment.go
- mediamtx.yml
> expose MTX_SEGMENT_DURATION to runOnRecordSegmentComplete (#3440) (#2983)

- internal/core/path.go
- internal/core/path_test.go
- internal/core/static_source_handler.go
- internal/defs/static_source.go
- internal/staticsources/hls/source.go
- internal/staticsources/hls/source_test.go
- internal/staticsources/rtmp/source.go
- internal/staticsources/rtmp/source_test.go
- internal/staticsources/rtsp/source.go
- internal/staticsources/rtsp/source_test.go
- internal/staticsources/srt/source.go
- internal/staticsources/srt/source_test.go
- internal/staticsources/udp/source.go
- internal/staticsources/udp/source_test.go
- internal/staticsources/webrtc/source.go
- internal/staticsources/webrtc/source_test.go
- internal/test/source_tester.go
- mediamtx.yml
this allows to pass query parameters to sources, for instance:
source: rtsp://my_host/my_path?$MTX_QUERY
sourceOnDemand: true
https://github.com/bluenviron/mediamtx/actions/runs/9571463402
> allow using MTX_QUERY inside source

- README.md
- internal/protocols/webrtc/incoming_track.go
- internal/protocols/webrtc/outgoing_track.go
- internal/protocols/webrtc/peer_connection_test.go
- internal/protocols/webrtc/tracks_to_medias.go
Fixes #3435
IMPORTANT NOTE: this doesn't allow to read H265 tracks with WebRTC, just to publish them. The inability to read H265 tracks with WebRTC is not in any way related to the server but depends on browsers and on the fact that they are not legally entitled to embed a H265 decoder inside them.
> webrtc: support publishing H265 tracks (#3435)

- internal/protocols/rtmp/reader.go
- internal/protocols/rtmp/reader_test.go
> rtmp: fix publishing from DJI FlightHub Sync (#3301)

- internal/servers/hls/hlsjsdownloader/main.go
In Windows, `go generate ./...` was causing a `ERR: hash mismatch` error.
To resolve this issue, I added a line to trim any whitespace from the `hashBuf`
errors no longer occur
> remove whitespace from hashBuf

- internal/servers/hls/index.html
> hls: fix playback speed on iOS (#3155) (#3731)

- internal/servers/srt/conn.go
just optimizes how the variable err is declared
> optimize var

- go.mod
- go.sum
- internal/conf/conf.go
- internal/conf/hls_variant.go
- internal/protocols/hls/from_stream.go
- internal/protocols/hls/from_stream_test.go
- internal/protocols/hls/to_stream.go
- internal/protocols/hls/to_stream_test.go
- internal/servers/hls/index.html
- internal/servers/hls/muxer_instance.go
- internal/servers/hls/server_test.go
- internal/staticsources/hls/source.go
Fixes #2728
This allows to generate HLS playlists and streams with multiple audio tracks. The embedded HLS player was improved with a button, displayed in the top right corner of the screen, that allows to change the audio track.
This has been tested with Chrome and Firefox. There are still compatibility issues with iOS.
https://github.com/bluenviron/mediamtx/actions/runs/10980959304
> hls: support generating streams with multiple audio tracks (#2728)

- README.md
- internal/api/api.go
- internal/api/api_test.go
- internal/auth/manager.go
- internal/auth/manager_test.go
- internal/defs/path.go
- internal/metrics/metrics.go
- internal/playback/on_get_test.go
- internal/playback/on_list_test.go
- internal/playback/server.go
- internal/pprof/pprof.go
- internal/servers/hls/http_server.go
- internal/servers/hls/server_test.go
- internal/servers/rtmp/conn.go
- internal/servers/rtmp/server_test.go
- internal/servers/rtsp/conn.go
- internal/servers/rtsp/session.go
- internal/servers/srt/conn.go
- internal/servers/srt/server_test.go
- internal/servers/webrtc/http_server.go
- internal/servers/webrtc/server.go
- internal/servers/webrtc/server_test.go
- internal/servers/webrtc/session.go
- internal/test/auth_manager.go
> support using JWT in Authorization header with API, Metrics, PProf (#3630)

- README.md
- go.mod
- go.sum
When an IP in webrtcAdditionalHosts is already present in the candidate list because webrtcIPsFromInterfaces is set to true (default), peer connection fails to establish. This is fixed.
> webrtc: fix connection timeout when webrtcAdditionalHosts is filled with existing IP

- go.mod
- internal/core/versiongetter/main.go
versiongetter does not work in Arch Linux's package build environment, because `repo.Log(&git.LogOptions{From: head.Hash()})` somehow returns `plumbing.ErrObjectNotFound`.
It might take some time before I can find out the root cause and submit a fix, so here's the preliminary change that wraps errors with additional context.
**Update: See the added comment in code.**
Fixes #3409.
> versiongetter: use a permissive AlternatesFS with git-go

- internal/protocols/webrtc/peer_connection.go
- internal/protocols/webrtc/to_stream_test.go
- internal/protocols/whip/client.go
- internal/servers/webrtc/publisher.js
- internal/servers/webrtc/reader.js
- internal/servers/webrtc/session.go
- internal/staticsources/webrtc/source_test.go
According to https://www.w3.org/TR/webrtc/#dictionary-rtcofferoptions-members ,
> Note
> Performing an ICE restart is recommended when [iceConnectionState](https://www.w3.org/TR/webrtc/#dom-peerconnection-ice-connection-state) transitions to "[failed](https://www.w3.org/TR/webrtc/#dom-rtciceconnectionstate-failed)". An application may additionally choose to listen for the [iceConnectionState](https://www.w3.org/TR/webrtc/#dom-peerconnection-ice-connection-state) transition to "[disconnected](https://www.w3.org/TR/webrtc/#dom-rtciceconnectionstate-disconnected)" and then use other sources of information (such as using [getStats](https://www.w3.org/TR/webrtc/#widl-RTCPeerConnection-getStats-Promise-RTCStatsReport--MediaStreamTrack-selector) to measure if the number of bytes sent or received …
> Restart ICE only on failed connection states

- README.md
- scripts/apidocs.mk
- scripts/binaries.mk
- scripts/dockerhub-legacy.mk
- scripts/dockerhub.mk
- scripts/format.mk
- scripts/lint.mk
- scripts/mod-tidy.mk
- scripts/test.mk
Thank you so incredibly much for creating MediaMTX! It's practically the perfect media server! I'd like to give back by fixing a few bugs and issues here. :)
**fix: improve unsafe path handling:**
Paths containing spaces or dashes were being interpreted as separate options, since the path handling lacked double quotes.
This fixes all unsafe instances of "PWD" and "HOME", along with all other unsafe paths in the scripts.
**readme: explicitly mount the configuration as read-only:**
This clearly shows users that the MediaMTX container will not modify the configuration file.
> fix: improve unsafe path handling

- internal/recorder/format_fmp4.go
Fixes #3969 
Fixes #4041
When a stream contained an Opus, MPEG-4 audio or AC3 track, timestamp in the segment file name was increasing at twice the speed.
> fix recording timestamp with some audio codecs (#3969) (#4041)

- internal/playback/on_get.go
- internal/playback/on_list.go
Replaces #3663
Segments are now parsed in parallel.
> playback: improve /list performance (#3663)

- internal/core/metrics_test.go
- internal/protocols/webrtc/peer_connection.go
- internal/servers/webrtc/reader.js
Fixes #4059
This fixes compatibility with devices that support decoding AV1 but doesn't support encoding it.
This was previously impossible to achieve due to a bug that prevented video from being displayed when recvonly transceivers were in use and audio was not present.
> webrtc: switch to recvonly transceivers (#4059)

- go.mod
Fixes "toolchain not available" error.
Before:
```
rtsp-simple-server$ go mod tidy
go: downloading go1.23 (linux/amd64)
go: download go1.23 for linux/amd64: toolchain not available
```
> go.mod: include .0 in version

- internal/protocols/rtmp/reader.go
- internal/protocols/rtmp/reader_test.go
> rtmp: fix compatibility with DJI Osmo Action 4 (#3802)

- scripts/binaries.mk
Error: 
```
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 8)
docker run --rm -v :/out \
temp sh -c "rm -rf /out/binaries && cp -r /s/binaries /out/"
docker: invalid spec: :/out: empty section between colons.
See 'docker run --help'.
make: *** [scripts/binaries.mk:65: binaries] Error 125
```
This pull request addresses the two issues in the `binaries.mk` file that prevent the proper building of binaries using Docker:
1. Legacy ENV format: The Dockerfile was using the legacy `ENV key value` format, which results in a warning. The newer `ENV key=value` format is recommended. This PR updates the line to follow the new format: Changed `ENV CGO_ENABLED 0` to E`NV CGO_ENABLED=0`.
2. Empty section in volume mount path: The `docker run` …
> Fix Dockerfile and docker run command for binary build

- internal/externalcmd/cmd_win.go
Fixed possible invalid process handle by using windows.OpenProcess instead. Fixes Issue https://github.com/bluenviron/mediamtx/issues/3980
> Bugfix Closes issue: 3980: Rewrote addProcessToGroup.

- internal/playback/on_list_test.go
- internal/recordstore/segment.go
- internal/recordstore/segment_test.go
fixes #4164 
Could probably use a test.  Sorry about the cruft of the messed up PR previously...
> Fix FindSegments when given a start time earlier than all available segments

- go.mod
- go.sum
Fixes #4161
when webrtcLocalTCPAddress is filled, webrtcAdditionalHosts is not empty and webrtcIPsFromInterfaces is false, connectivity was impossible to achieve.
> webrtx: fix connectivity regression (#4161)

- go.mod
- go.sum
Fixes #4150 
When MediaMTX is running on Windows and the machine has an IPv6, connectivity was impossible to achieve.
> webrtc: fix connectivity regression on Windows (#4150)

- go.mod
- go.sum
- internal/protocols/rtmp/reader.go
> hls: fix reading AV1 from OBS+WHIP (#3886)

- internal/protocols/webrtc/peer_connection.go
- internal/servers/webrtc/publisher.js
- internal/servers/webrtc/reader.js
> webrtc: fix detecting closure of some sessions (#4204)

- internal/servers/rtsp/conn.go
- internal/servers/rtsp/server.go
> fix freeze when getting metrics and a RTSP connection is being created (#4179)

- internal/recordcleaner/cleaner.go
- internal/recordcleaner/cleaner_test.go
> fix removing empty recording folders (#4227)

- internal/core/core.go
> record: fix crash when recordDeleteAfter is 0 and API is called (#4250)

- internal/conf/conf.go
- internal/conf/conf_test.go
when rtspAuthMethods is nil, digest+SHA256 gets enabled, resulting in the inability of FFmpeg and most clients to connect due to compatibility issues.
> rtsp: fix authentication when rtspAuthMethods is empty

- internal/staticsources/rpicamera/camera.go
```
38.61 # github.com/bluenviron/mediamtx/internal/staticsources/rpicamera
38.61 internal/staticsources/rpicamera/camera.go:169:23: undefined: h264.AnnexBUnmarshal
```
Build failed because rpicamera imported mediacommon v2 package, which deprecated and removed h264.AnnexBUnmarshal function.
> fix for build failure caused by deprecated h264.AnnexBUnmarshal

- internal/core/path.go
- internal/defs/path.go
- internal/servers/rtsp/conn.go
- internal/servers/rtsp/session.go
- internal/servers/webrtc/server_test.go
- internal/servers/webrtc/session.go
Switch from 'no one is publishing to path' to 'no stream is available on path' since the stream might be provided from a static source too.
> change error message when stream is not found

- internal/stream/stream.go
- internal/stream/stream_format.go
- internal/stream/stream_media.go
Stream errors include both errors from decoding RTP packets into frames, and errors from encoding frames into RTP packets. "processing errors" is more fit.
> rename stream decode errors into processing errors

- internal/servers/webrtc/reader.js
Fix error "A BUNDLE group contains a codec collision for payload_type='96. All codecs must share the same type, encoding name, clock rate and parameters. (INVALID_PARAMETER)"
> webrtc: fix codec collision in Chrome

- README.md
> readme: duration is a float, not a string

- internal/auth/manager.go
- internal/auth/manager_test.go
- internal/conf/conf.go
- internal/core/core.go
- mediamtx.yml
In order to overcome the issue in #3430 and probably for other use cases as well I added an authJWTExclude parameter that functions the same as authHTTPExclude. So actions can be excluded from the JWT authentication
> Exclude actions when using JWT authentication

- internal/api/api.go
- internal/core/core.go
- internal/core/path.go
- internal/core/path_manager.go
- internal/defs/api.go
- internal/metrics/metrics.go
- internal/servers/hls/server.go
- internal/servers/hls/server_test.go
- internal/servers/rtmp/server.go
- internal/servers/rtsp/server.go
- internal/servers/srt/server.go
- internal/servers/webrtc/server.go
When hlsAlwaysRemux was switched from false to true, through API or hot reloading, muxers of existing paths were not created. This fixes the issue.
> hls: fix toggling hlsAlwaysRemux after server is started

- apidocs/openapi.yaml
- internal/api/api.go
- internal/api/api_test.go
- internal/auth/manager.go
- internal/auth/manager_test.go
- internal/test/auth_manager.go
Hi all, this is my first contribution and should addresses #4452. The only blaring issue is that the endpoint still requires a JWT signed with a key from the outdated JWKS, but more than open to feedback.
Changes include:
- Seperating refresh and pulling of JWKS tokens
- Add `/auth/jwks/refresh` endpoint for force refreshing the JWKS token
- Updated OpenAPI Schema definition
> Feat: Add JWKS rotation API endpoint

- internal/core/api_test.go
- internal/core/metrics_test.go
- internal/core/path_test.go
- internal/protocols/rtmp/conn.go
- internal/protocols/rtmp/conn_test.go
- internal/protocols/rtmp/from_stream.go
- internal/protocols/rtmp/reader.go
- internal/protocols/rtmp/reader_test.go
- internal/protocols/rtmp/writer.go
- internal/protocols/rtmp/writer_test.go
- internal/servers/rtmp/conn.go
- internal/servers/rtmp/server_test.go
- internal/staticsources/rtmp/source.go
- internal/staticsources/rtmp/source_test.go
when reading, the "connect" command should not contain fpad, capabilities, audioCodecs, videoCodecs, videoFunction.
> rtmp: fix connect command when reading

- internal/conf/path.go
> allow using colon in path names (#4377)

- internal/playback/muxer_fmp4.go
- internal/playback/on_get_test.go
this happened when recording has B-frames, playback format is fmp4 and starting position doesn't correspond to a IDR frame.
> playback: fix jerky video

- .github/workflows/nightly_binaries.yml
- .github/workflows/release.yml
this allows to prove that binaries were produced by GitHub actions.
> add attestation system to protect binaries (#4012)

- internal/servers/webrtc/http_server.go
Prevent a bug in Firefox in which, when the page is loaded in an iframe and the iframe is deleted and recreated, WebRTC is unable to re-establish the connection.
> webrtc: fix re-establishing connection in iframe

- internal/core/path.go
- internal/core/path_manager.go
- internal/defs/path.go
- internal/servers/hls/http_server.go
- internal/servers/hls/server_test.go
- internal/servers/rtmp/conn.go
- internal/servers/rtmp/server.go
- internal/servers/rtmp/server_test.go
- internal/servers/rtsp/conn.go
- internal/servers/rtsp/server.go
- internal/servers/rtsp/server_test.go
- internal/servers/rtsp/session.go
- internal/servers/srt/conn.go
- internal/servers/srt/server.go
- internal/servers/srt/server_test.go
- internal/servers/webrtc/http_server.go
- internal/servers/webrtc/server.go
- internal/servers/webrtc/server_test.go
- internal/servers/webrtc/session.go
- internal/test/path_manager.go
decrease the number of ways in whihch path manager can be accessed.
> remove PathManager.StartPublisher and StopPublisher

- README.md
- internal/staticsources/udp/source.go
... instead of listening on all multicast interfaces.
Fixes #4565
> udp: listen on default multicast interface (#4565)

- internal/staticsources/hls/source_test.go
- internal/staticsources/mpegts/source.go
- internal/staticsources/mpegts/source_test.go
- internal/staticsources/rtmp/source_test.go
- internal/staticsources/rtp/source.go
- internal/staticsources/rtp/source_test.go
- internal/staticsources/rtsp/source_test.go
- internal/staticsources/srt/source_test.go
- internal/staticsources/webrtc/source.go
- internal/staticsources/webrtc/source_test.go
When a path has a MPEG-TS, RTP or WebRTC source and the path configuration is reloaded, a routine was left open because the reload channel was not handled. This fixes the issue.
> fix memory leak when reloading the configuration

- internal/protocols/webrtc/peer_connection.go
- internal/protocols/webrtc/peer_connection_test.go
- internal/protocols/webrtc/to_stream_test.go
- internal/protocols/whip/client.go
- internal/protocols/whip/client_test.go
- internal/servers/webrtc/session.go
- internal/staticsources/webrtc/source.go
- internal/staticsources/webrtc/source_test.go
contexts are useless since there's already PeerConnection.Close().
> remove context from webrtc.PeerConnection arguments

- internal/protocols/rtmp/chunk/chunk0.go
- internal/protocols/rtmp/chunk/chunk1.go
- internal/protocols/rtmp/rawmessage/reader.go
- internal/protocols/rtmp/rawmessage/writer.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
> refactor: use the built-in max/min to simplify the code

- internal/servers/hls/index.html
- internal/servers/webrtc/read_index.html
Add disablepictureinpicture param to optionally hide the PiP button that floats over video
ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/video#disablepictureinpicture
Note that Firefox hides the floating button, but PiP can still be chosen from the context menu, while Chrome disables the floating button and the context menu item.
I did not fully build mediamtx and test this. Only tested using web developer tools to change the running page.
> Add disablepictureinpicture param

- internal/protocols/rtmp/message/message.go
- internal/protocols/rtmp/message/msg_acknowledge.go
- internal/protocols/rtmp/message/msg_set_chunk_size.go
- internal/protocols/rtmp/message/msg_set_peer_bandwidth.go
- internal/protocols/rtmp/message/msg_set_window_ack_size.go
- internal/protocols/rtmp/message/msg_user_control_ping_request.go
- internal/protocols/rtmp/message/msg_user_control_ping_response.go
- internal/protocols/rtmp/message/msg_user_control_set_buffer_length.go
- internal/protocols/rtmp/message/msg_user_control_stream_begin.go
- internal/protocols/rtmp/message/msg_user_control_stream_dry.go
- internal/protocols/rtmp/message/msg_user_control_stream_eof.go
- internal/protocols/rtmp/message/msg_user_control_stream_is_recorded.go
- internal/protocols/rtmp/message/reader_test.go
MediaMTX strictly enforces RTMP specification requiring control messages to use Chunk Stream ID 2, causing connection failures with many IP cameras and PTZ cameras that use non-standard implementations.
- Added flexible `isControlChunkStreamID()` validation function
- Support common non-standard Chunk Stream IDs (2, 3, 4, 5, 6) used by various camera manufacturers
- Maintain full backward compatibility with standard RTMP clients
- Centralized compatibility management for easy extension
- **Core**: Added `isControlChunkStreamID()` helper function in `message.go`
- **Control Messages**: Updated all control message validation logic
- **Compatibility**: Support Chunk Stream IDs 2, 3, 4, 5, 6
- **Error Messages**: Improved error reporting with specific Chunk Stream ID values
- PTZ cameras …
> feat: improve RTMP control message compatibility with non-standard cameras

- internal/auth/manager.go
- internal/auth/manager_test.go
Usernames and passwords must be requested explicitly to clients, but they were not in case of JWTs. This fixes the issue.
> fix reading JWT when it is passed through the password field

- internal/auth/manager.go
- mediamtx.yml
This is the first step into removing support for passing JWTs through query parameters, which is a security flaw.
> stop accepting JWTs from query parameters unless allowed in conf

- internal/servers/rtsp/session.go
Fixes #5030 
sometimes sessions have an empty associated path, and this caused a crash.
> api: fix crash in rtspsessions/list and /rtspsessions/get (#5030)

- api/openapi.yaml
- docs/2-usage/18-control-api.md
- internal/api/api.go
- internal/api/api_test.go
- internal/core/core.go
- internal/defs/api.go
- internal/playback/on_get_test.go
- internal/playback/on_list_test.go
- internal/recordstore/path_test.go
- internal/testapidocs/apidocs_test.go
> api: add /info endpoint (#945)
